// Placeholder images to avoid CORS issues with external URLs
export const placeholderImages = {
  // Avatar placeholders (base64 encoded simple SVGs)
  avatar1: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTUwIiBoZWlnaHQ9IjE1MCIgdmlld0JveD0iMCAwIDE1MCAxNTAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxNTAiIGhlaWdodD0iMTUwIiBmaWxsPSIjNEY0NjU0Ii8+CjxjaXJjbGUgY3g9Ijc1IiBjeT0iNjAiIHI9IjI1IiBmaWxsPSIjOUNBM0FGIHN0cm9rZT0iI0ZGRiIgc3Ryb2tlLXdpZHRoPSIyIi8+CjxwYXRoIGQ9Ik0zMCAxMzBDMzAgMTEwIDQ4IDk1IDc1IDk1UzEyMCAxMTAgMTIwIDEzMFYxNTBIMzBWMTMwWiIgZmlsbD0iIzlDQTNBRiIgc3Ryb2tlPSIjRkZGIiBzdHJva2Utd2lkdGg9IjIiLz4KPC9zdmc+",
  avatar2: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTUwIiBoZWlnaHQ9IjE1MCIgdmlld0JveD0iMCAwIDE1MCAxNTAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxNTAiIGhlaWdodD0iMTUwIiBmaWxsPSIjMzc0MTUxIi8+CjxjaXJjbGUgY3g9Ijc1IiBjeT0iNjAiIHI9IjI1IiBmaWxsPSIjNjM3Mzg0IiBzdHJva2U9IiNGRkYiIHN0cm9rZS13aWR0aD0iMiIvPgo8cGF0aCBkPSJNMzAgMTMwQzMwIDExMCA0OCA5NSA3NSA5NVMxMjAgMTEwIDEyMCAxMzBWMTUwSDMwVjEzMFoiIGZpbGw9IiM2MzczODQiIHN0cm9rZT0iI0ZGRiIgc3Ryb2tlLXdpZHRoPSIyIi8+Cjwvc3ZnPg==",
  avatar3: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTUwIiBoZWlnaHQ9IjE1MCIgdmlld0JveD0iMCAwIDE1MCAxNTAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxNTAiIGhlaWdodD0iMTUwIiBmaWxsPSIjNDMzODFCIi8+CjxjaXJjbGUgY3g9Ijc1IiBjeT0iNjAiIHI9IjI1IiBmaWxsPSIjQjQ1MzA5IiBzdHJva2U9IiNGRkYiIHN0cm9rZS13aWR0aD0iMiIvPgo8cGF0aCBkPSJNMzAgMTMwQzMwIDExMCA0OCA5NSA3NSA5NVMxMjAgMTEwIDEyMCAxMzBWMTUwSDMwVjEzMFoiIGZpbGw9IiNCNDUzMDkiIHN0cm9rZT0iI0ZGRiIgc3Ryb2tlLXdpZHRoPSIyIi8+Cjwvc3ZnPg==",
  avatar4: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTUwIiBoZWlnaHQ9IjE1MCIgdmlld0JveD0iMCAwIDE1MCAxNTAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxNTAiIGhlaWdodD0iMTUwIiBmaWxsPSIjNTQ0MDQzIi8+CjxjaXJjbGUgY3g9Ijc1IiBjeT0iNjAiIHI9IjI1IiBmaWxsPSIjQjQ1MzA5IiBzdHJva2U9IiNGRkYiIHN0cm9rZS13aWR0aD0iMiIvPgo8cGF0aCBkPSJNMzAgMTMwQzMwIDExMCA0OCA5NSA3NSA5NVMxMjAgMTEwIDEyMCAxMzBWMTUwSDMwVjEzMFoiIGZpbGw9IiNCNDUzMDkiIHN0cm9rZT0iI0ZGRiIgc3Ryb2tlLXdpZHRoPSIyIi8+Cjwvc3ZnPg==",
  avatar5: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTUwIiBoZWlnaHQ9IjE1MCIgdmlld0JveD0iMCAwIDE1MCAxNTAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxNTAiIGhlaWdodD0iMTUwIiBmaWxsPSIjMzIyNzVCIi8+CjxjaXJjbGUgY3g9Ijc1IiBjeT0iNjAiIHI9IjI1IiBmaWxsPSIjNzk3MEIwIiBzdHJva2U9IiNGRkYiIHN0cm9rZS13aWR0aD0iMiIvPgo8cGF0aCBkPSJNMzAgMTMwQzMwIDExMCA0OCA5NSA3NSA5NVMxMjAgMTEwIDEyMCAxMzBWMTUwSDMwVjEzMFoiIGZpbGw9IiM3OTcwQjAiIHN0cm9rZT0iI0ZGRiIgc3Ryb2tlLXdpZHRoPSIyIi8+Cjwvc3ZnPg==",

  // Project image placeholders
  forest: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAwIiBoZWlnaHQ9IjMwMCIgdmlld0JveD0iMCAwIDUwMCAzMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSI1MDAiIGhlaWdodD0iMzAwIiBmaWxsPSIjRUNGMEY0Ii8+CjxyZWN0IHk9IjI1MCIgd2lkdGg9IjUwMCIgaGVpZ2h0PSI1MCIgZmlsbD0iIzY1QTMwRCIvPgo8Y2lyY2xlIGN4PSIxMDAiIGN5PSIxODAiIHI9IjQwIiBmaWxsPSIjMjJDNTVFIi8+CjxjaXJjbGUgY3g9IjIwMCIgY3k9IjE2MCIgcj0iNDUiIGZpbGw9IiMyMkM1NUUiLz4KPGF0aC8kNTAiCjxjaXJjbGUgY3g9IjMwMCIgY3k9IjE3MCIgcj0iNDAiIGZpbGw9IiMyMkM1NUUiLz4KPGF0aC8kNDgiCjxjaXJjbGUgY3g9IjQwMCIgY3k9IjE1MCIgcj0iNDIiIGZpbGw9IiMyMkM1NUUiLz4KPGF0aC8kNjAiCjxyZWN0IHg9Ijk1IiB5PSIyMDAiIHdpZHRoPSIxMCIgaGVpZ2h0PSI1MCIgZmlsbD0iIzkyNDAwRSIvPgo8cmVjdCB4PSIxOTUiIHk9IjE4NSIgd2lkdGg9IjEwIiBoZWlnaHQ9IjY1IiBmaWxsPSIjOTI0MDBFIi8+CjxyZWN0IHg9IjI5NSIgeT0iMTkwIiB3aWR0aD0iMTAiIGhlaWdodD0iNjAiIGZpbGw9IiM5MjQwMEUiLz4KPHN5ZWN0IHg9IjM5NSIgeT0iMTcwIiB3aWR0aD0iMTAiIGhlaWdodD0iODAiIGZpbGw9IiM5MjQwMEUiLz4KPC9zdmc+",
  solar: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAwIiBoZWlnaHQ9IjMwMCIgdmlld0JveD0iMCAwIDUwMCAzMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSI1MDAiIGhlaWdodD0iMzAwIiBmaWxsPSIjRkVGM0M3Ii8+CjxjaXJjbGUgY3g9IjQwMCIgY3k9IjgwIiByPSIzMCIgZmlsbD0iI0Y1OTE1RSIvPgo8cGF0aCBkPSJNMjAwIDIwMEgzMDBWMjUwSDIwMFYyMDBaIiBmaWxsPSIjMUY0ODg4Ii8+CjxwYXRoIGQ9Ik0xNTAgMTgwSDM1MFYyMDBIMTUwVjE4MFoiIGZpbGw9IiMxRjQ4ODgiLz4KPHN0aHRkPSJNMTAwIDE2MEg0MDBWMTU4MEhMTwxNjBaIiBmaWxsPSIjMUY0ODg4Ii8+CjwmZz48Ii9zdmc+",
  wind: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAwIiBoZWlnaHQ9IjMwMCIgdmlld0JveD0iMCAwIDUwMCAzMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSI1MDAiIGhlaWdodD0iMzAwIiBmaWxsPSIjRjNGNEY2Ii8+CjxyZWN0IHg9IjIwMCIgeT0iMTUwIiB3aWR0aD0iMTAiIGhlaWdodD0iMTAwIiBmaWxsPSIjRkZGIi8+CjxwYXRoIGQ9Ik0yMDAgMTUwTDI1MCA4MFYxMzBMMjIwIDEyNUwyMDAgMTUwWiIgZmlsbD0iI0ZGRiIvPgo8cGF0aCBkPSJNMjEwIDE1MEwyNzAgMTAwVjE0MEwyMzAgMTM1TDIxMCAxNTBaIiBmaWxsPSIjRkZGIi8+CjxwYXRoIGQ9Ik0yMDAgMTYwTDE1MCA5MFYxNDBMMTgwIDEzNUwyMDAgMTYwWiIgZmlsbD0iI0ZGRiIvPgo8L3N2Zz4=",
  conservation: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAwIiBoZWlnaHQ9IjMwMCIgdmlld0JveD0iMCAwIDUwMCAzMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSI1MDAiIGhlaWdodD0iMzAwIiBmaWxsPSIjRUNGREY1Ii8+CjxjaXJjbGUgY3g9IjI1MCIgY3k9IjE1MCIgcj0iODAiIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzIyQzU1RSIgc3Ryb2tlLXdpZHRoPSI0Ii8+CjxwYXRoIGQ9Ik0yMjAgMTMwSDI4MFYxNzBIMjIwVjEzMFoiIGZpbGw9IiMxNkE2NUMiLz4KPGF0aC8+CjwmZXZnPg=="
};

export const getAvatarPlaceholder = (index) => {
  const avatars = [
    placeholderImages.avatar1,
    placeholderImages.avatar2,
    placeholderImages.avatar3,
    placeholderImages.avatar4,
    placeholderImages.avatar5
  ];
  return avatars[index % avatars.length];
};

export const getProjectPlaceholder = (type) => {
  switch (type) {
    case 'reforestation':
    case 'forest':
      return placeholderImages.forest;
    case 'renewable-energy':
    case 'solar':
      return placeholderImages.solar;
    case 'wind':
      return placeholderImages.wind;
    case 'conservation':
    default:
      return placeholderImages.conservation;
  }
};

// Additional exported functions that are imported in other files
export const getPlaceholderAvatar = getAvatarPlaceholder;
export const getPlaceholderProjectImage = getProjectPlaceholder;
